# 6 异常的捕获及处理

## 6.1 认识异常

## 6.2 处理异常
* Java针对异常的处理提供了3个核心关键字：**try**、**catch**、**finally**。
```java
try {
    有可能出现的异常语句;
} catch (异常类型 对象) {
    异常处理;
} catch (异常类型 对象) {
    异常处理;
} finally {
    不管是否出现异常，都执行的统一代码;
}
```

* 为了能够进行异常的处理，可以使用异常类中提供的**printStackTrace()**方法进行异常信息的完整输出。
```java
public class TestDemo {
    public static void main(String args[]) {
        try {
            System.out.println("除法计算：" + (10 / 0));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

## 6.3 异常的处理流程
所有异常类型的**最高继承类**是**java.lang.Throwable**，并且在Throwable下有**两个子类**：
* **Error**：指的是**JVM错误**，这时的**程序并没有执行**，无法处理。
* **Exception**：指的是**程序运行中产生的异常**，用户可以使用异常处理格式处理。

示例：
* `System.out.println("Hello World!")`语句少写了一个分号，则会报`java.lang.Error`
* `System.out.println(11/0)`除数为0，则会报`java.lang.ArithmeticException`

**Java中异常处理的完整流程**：
1. 当程序在运行中**出现了异常**，会由**JVM**自动**根据异常的类型实例化**一个与之类型匹配的**异常类对象**。
2. 产生异常对象后会**判断**当前语句**是否存在异常处理**，如果**没有**异常处理，就**交给JVM进行默认的异常处理**，默认处理方式为：**输出异常信息，而后结束程序的调用**。
3. 如果**存在**异常的捕获操作，就先由**try**语句来**捕获**产生的**异常类实例化对象**，再与try之后的每一个**catch**进行**比较**，如果有**符合**的捕获类型，则使用当前**catch语句来进行异常的处理**，如果**不匹配**则**向下继续匹配**其他catch。
4. 不管最后异常处理是否能够匹配，都要向后执行，如果此逝程序中存在**finally**语句，则先**执行finally中的代码**，如果**没有匹配异常**，则将此异常**交给JVM进行默认处理**。

Tips：**处理多个异常**时，**捕获范围小的异常要放在捕获范围大的异常之前**处理。

## 6.4 throws关键字
* **throws**关键字主要在**方法定义**上使用，表示此**方法中不进行异常的处理**，而是**交给被调用处处理**，**调用处一定要处理**被抛出的异常。
```java
class MyMath {
    public static int div(int x,int y) throws Exception {
        return x / y;
    }
}
public class TestDemo {
    public static void main(String args[]) {
        try {
            System.out.println(MyMath.div(12 / 2));
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
}
```

## 6.5 throw关键字
* ***throw***：用户可以**人为地抛出**一个**实例化异常对象**。

## 6.6 异常处理的标准格式

## 6.7 RuntimeException类
* 在Java中为了方便用户代码的编写，专门提供了一种**RuntimeException**类。这种类程序在编译时**不会强制性的要求用户处理异常**，用户可以根据自己的需要有选择性地进行处理，但是如果**没有处理又发生异常了**，将**交给JVM默认处理**。例如Integer类中的字符串转换方法：`public static int parseInt(String s) throws NumberFormatException`这个异常类就属于RuntimeException子类。

一些常见的RuntimeException：
* NumberFormatException
* ClassCastException
* NullPointerException
* ArithmeticException
* ArrayIndexOutOfBoundsException

## 6.8 assert关键字
* assert主要功能是进行断言，断言指的是程序执行到某行之后，其结果一定是预期的结果。

## 6.9 自定义异常
* 有时候Java提供的异常在实际工作中并不够使用，所以用户需要自己去开发一个异常类，想要实现自定义异常类，只需要继承Exception类或者RuntimeException类即可。
```java
class MyException extends exception {
    public addException(String s) {
        super(s);
    }
}
```